{% set name = "numpydantic" %}
{% set version = "1.6.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/numpydantic-{{ version }}.tar.gz
  sha256: d8e0d29d4a39f6ac190376eb96de6c8a5e29277db2c3ecc3aab8e85384ebfb47

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pdm-backend
    - pip
  run:
    - python >={{ python_min }},<4.0
    - pydantic >=2.3.0
    - numpy >=1.24.0
    - typing-extensions >=4.11.0

test:
  imports:
    - numpydantic
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/p2p-ld/numpydantic
  summary: Type and shape validation and serialization for numpy arrays in pydantic models
  license: MIT
  license_file: LICENSE
  doc_url: https://numpydantic.readthedocs.io/
  dev_url: https://github.com/p2p-ld/numpydantic

extra:
  recipe-maintainers:
    - sneakers-the-rat
    - apcamargo
