{% set name = "numpydantic" %}
{% set version = "1.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/numpydantic-{{ version }}.tar.gz
  sha256: 52c5bbe9f52f0f8f10b77a4bd0c0a867074cddc473174f1083533e29dd1b5b60

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python <4.0,>=3.9
    - pdm-backend
    - pip
  run:
    - python <4.0,>=3.9
    - pydantic >=2.3.0
    - numpy >=1.24.0
    - typing-extensions >=4.11.0

test:
  imports:
    - numpydantic
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/p2p-ld/numpydantic
  summary: Type and shape validation and serialization for numpy arrays in pydantic models
  license: MIT
  license_file: LICENSE
  doc_url: https://numpydantic.readthedocs.io/
  dev_url: https://github.com/p2p-ld/numpydantic

extra:
  recipe-maintainers:
    - sneakers-the-rat
    - apcamargo
